language: cpp
arch:
- amd64
- arm64
os:
- linux
- osx
compiler:
- gcc
jobs:
  fast_finish: true
  include:
  - os: linux
    arch: amd64
  - os: linux
    arch: arm64
  - os: osx
addons:
  apt:
    packages:
    - libgtk-3-dev
    - nasm
before_script:
- mkdir build
- cd build
- cmake ..
script: make
before_deploy:
- mkdir deploy
- if [ $TRAVIS_OS_NAME = osx ]; then cp libopenpnp-capture.dylib deploy; cp mac/tests/openpnp-capture-test
  deploy/openpnp-capture-test-mac; fi
- if [ $TRAVIS_OS_NAME = linux ]; then cp libopenpnp-capture.so deploy; cp linux/tests/openpnp-capture-test
  deploy/openpnp-capture-test-linux; fi
- if [ $TRAVIS_CPU_ARCH = arm64 ]; then cp libopenpnp-capture.so deploy/libopenpnp-capture-arm64.so;
  cp linux/tests/openpnp-capture-test deploy/openpnp-capture-test-linux-arm64; fi
deploy:
  provider: releases
  token:
    secure: STRLCocxCYsorDqYtC4+LOOh+HO6xeBwc83OjO+urXOrWcbpg5UlNGsMK7E66v7XiiGgfVRFV2nQK79dKLrC3OAboRkQYsdUHbotRms6CRhBQYf03AjAitfgQDKGlUDvMrTJsf7CWy8ZCW4PgYnn1Ui9LAXqTAi724DZ+Bcr7yzCyrlJWfYsdrv2Nok2q5AuhhftRU4zb63tFFME4NM23zEMq7ZbEF5DkMZrVltFGfE98gzpju1sFC/2fWHGEeKL775BtU8KOHV1RqAKxFz6VZsCe5By6YlG4yOFEQGfPdpZF8R4jMdl2b8bEJcXdp4ShfFnpkSsT67jiGDusc7fwyeETmQ8+dYohjFN1HxMhg82G3iPDPPWVtIhc80OWhcl/ua6pKCxEV7VBFfyBOxhJ0mRkx8J5mF+X3ZzRVDQ8xUmv0+w1ZPKA/VHIbVdL0zqREn5+30lqrc6d8lc+aQGNFxUUi9I0sjXpSM3dynl0HfRdYUu+9I3XkdXhvgCGUhp0AxhZ9gTq+ZQdBByioJizx5WrJ4IvEYVQSjwlO/bMELEiYLSD8EItkLqkAU/0pf1r2l1Up3H4xPYBDl4hXr/d+376IfU67uCEYk43SXeUVy1Y9xQDo7Km5VY6NobOSLt9ozcIaR+mR8+d8T0lUxwE1f5PSS9DIh59ZHQskZYCUc=
  file_glob: true
  file: deploy/*
  cleanup: false
  edge: true
  on:
    all_branches: true
    tags: true
