language: cpp
dist: bionic
arch:
- amd64
- arm64
os:
- linux
- osx
compiler:
- gcc
jobs:
  fast_finish: true
  include:
  - os: linux
    arch: amd64
  - os: linux
    arch: arm64
  - os: osx
addons:
  apt:
    packages:
    - libgtk-3-dev
    - nasm
    - build-essential
    - cmake
    - libjpeg-dev
before_script:
- mkdir build
- cd build
- cmake ..
script: make
before_deploy:
- mkdir deploy
- if [ $TRAVIS_OS_NAME = osx ]; then cp libopenpnp-capture.dylib deploy; cp mac/tests/openpnp-capture-test
  deploy/openpnp-capture-test-mac; fi
- if [ $TRAVIS_OS_NAME = linux ]; then cp libopenpnp-capture.so deploy; cp linux/tests/openpnp-capture-test
  deploy/openpnp-capture-test-linux; fi
- if [ $TRAVIS_CPU_ARCH = arm64 ]; then cp libopenpnp-capture.so deploy/libopenpnp-capture-arm64.so;
  cp linux/tests/openpnp-capture-test deploy/openpnp-capture-test-linux-arm64; fi
deploy:
  provider: releases
  token:
    secure: bDSMOH/IdfNfc8eKT7alPn1ON9A2f+ffHssTCUfHB4ziOdtQyKAHNgwkmFutbkSQg6rgW0nZvgq+tBl26SwOKJO9KHQf2HnlT8X6KvI+Y5LC672joDcUToR2PAejgrMnneglKfweAi8ePB+OQNbFtGWrlZUgLJURCHZ1FhYib07IPVob3NjAU26+fgnWzDhEblTG9XHPATZBpaCfeX3TIbqfYWWj++A0V9TJkVLk8LNNcPzt1P73PeTl9p5PQj1Wv/Zak+AgqfqQC4kMmC/84thAJO0o9Z1Tih5uTNneYA83mUy6LMg1QxlG9qIfWouY1Hkr/vcIBYa9t6GdoCYFT9EIl8OGq1uzb7Ga0BUxyN9+/VkSDx0+JQ8GieaoUantunjwj8y5/bk99Pagab1/z7Hv60D1Rm9BkfsrLGRB5VQq1Mn5O/UqhpwvbWmiQlBXg4hdjUrCRSN/Pz3HMTAEFyEmttyyL63bgnHp9P6BZWvJUQ3zcuxe1fUdKwzqilmom3/4cZ5qi9FOB7Jto4H6j0wX5u+x1/m8u4/W+VdXckyaH5t6rZDAqxk7weZQwyD4P94VZUssb5xUI5P07N4j4YWw4i4nVcvipJ4H9vfx94qO/7TB012E9dHoPsZN0daDWaG9gRJKloHvSTTgcZBRP3/R7RYvSPQInUoG6/g5Ras=
  file: deploy/*
  edge: true
  on:
    branch: rpi3-arm64
