name: buildx

on:
  pull_request:
    branches: master
  push:
    branches: ["master", "rpi3-arm64"]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: Run Buildx and publish the container to GitHub packages
        run: |
          VERSION=$(date +%s)
          docker buildx build \
            --platform linux/arm64 \
            --output "type=image,push=true" \
            --file ./docker/Dockerfile.rpi3_arm64 \
            --tag docker.pkg.github.com/cchs-melbourne/openpnp-capture:$VERSION .
          docker push docker.pkg.github.com/cchs-melbourne/openpnp-capture:$VERSION